### ISSUE TITLE
The usage of mahimahi about "mm-ge-loss"

### ISSUE THREAD

**Issue by Roger-Fpeng** [Thesys-lab/tambur#1]
I install mahimahi in my ubuntu, but there is no "mm-ge-loss" command. There is also no description about "mm-ge-loss" on the [manpage](https://manpages.ubuntu.com/manpages/focal/man1/mahimahi.1.html) of mahimahi.

**Comment by pkarimib** [comment]
@PFpengfeng what was the solution?
